<a href="https://colab.research.google.com/github/LeoisWTT/PHYS3151-Machine-Learning-in-Physics-2023/blob/main/feedforward-neural-network/perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A python Perceptron to perfrom logical gate AND
<br>  A   B  |  AND
<br>  0   0  |   0
<br>  0   1  |   0
<br>  1   0  |   0
<br>  1   1  |   1
<br> Here we use binary activation function: 
<br> $y=0$ if $\vec{w}\cdot\vec{x}+b \le 0$
<br> $y=1$ if $\vec{w}\cdot \vec{x}+b > 0$

In [ ]:
import numpy as np

class Perceptron():
    
# initialize the weights to 0.
    def __init__(self, no_of_inputs, threshold=8, learning_rate=0.1):
        self.threshold = threshold
        self.learning_rate = learning_rate
        self.weights = np.zeros(no_of_inputs + 1)
        
# for each set of inputs in the training examples, perceptron will predict an output
    def predict(self, inputs):
        summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
        if summation > 0:
            activation = 1
        else:
            activation = 0
        return activation
    
# Compare it to the expected output
# Update its weights, if the expected output != the actual output
# for error e = y - f(x), there are only three values, given any x
#    y  f(x) | y - f(x)
#    1    1  |   0
#    0    0  |   0
#    1    0  |   1
#    0    1  |  -1


    def train(self, training_inputs, labels):
        print(self.weights)
        for _ in range(self.threshold):
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learning_rate * (label - prediction) * inputs
                self.weights[0] += self.learning_rate * (label - prediction)
                print(self.weights)
                

In [ ]:
import numpy as np
#from perceptron import Perceptron

training_inputs = []
training_inputs.append(np.array([1,1]))
training_inputs.append(np.array([1,0]))
training_inputs.append(np.array([0,1]))
training_inputs.append(np.array([0,0]))

labels = np.array([1,0,0,0])

perceptron = Perceptron(2)
perceptron.train(training_inputs, labels)

inputs = np.array([1,1])
print(perceptron.predict(inputs))

inputs = np.array([-2,-5])
print(perceptron.predict(inputs))

inputs = np.array([2,2])
print(perceptron.predict(inputs))

inputs = np.array([0,0])
print(perceptron.predict(inputs))

[0. 0. 0.]
[0.1 0.1 0.1]
[0.  0.  0.1]
[-0.1  0.   0. ]
[-0.1  0.   0. ]
[0.  0.1 0.1]
[-0.1  0.   0.1]
[-0.1  0.   0.1]
[-0.1  0.   0.1]
[0.  0.1 0.2]
[-0.1  0.   0.2]
[-0.2  0.   0.1]
[-0.2  0.   0.1]
[-0.1  0.1  0.2]
[-0.1  0.1  0.2]
[-0.2  0.1  0.1]
[-0.2  0.1  0.1]
[-0.1  0.2  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
[-0.2  0.1  0.2]
1
0
1
0
